### ISSUE TITLE
Rezervacije trenutnega tedna v urniku splošnega tedna

### ISSUE THREAD

**Issue by jaanos** [ul-fmf/urnik#107]
Kot rečeno v #104, bi bilo dobro, če bi se tudi v urniku splošnega tedna prikazovale rezervacije trenutnega tedna, in sicer na tak način, da je jasno razvidna razlika od rednih terminov, in da se da njihov prikaz izklopiti. Prav tako bi bilo fino, če se lahko redni termini odpovejo.

Malo sem se poigral - lahko bi izgledalo nekako tako:
![urnik-rez](https://user-images.githubusercontent.com/6708236/95767008-613d8380-0cb4-11eb-8452-a4080bcf3cd0.png)
Za odpovedani termin sem uporabil sledeči CSS/SVG (prirejeno po http://jsfiddle.net/02ffvyeo/ - lahko se še malo polepša):
```css
.preklicano {
    background: url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' version='1.1' preserveAspectRatio='none' viewBox='0 0 100 100'><path d='M100 0 L0 100 ' stroke='red' stroke-width='2'/><path d='M0 0 L100 100 ' stroke='red' stroke-width='2'/></svg>");
    background-repeat:no-repeat;
    background-position:center center;
    background-size: 100% 100%, auto;
}
```
